---
title: "Sentiment_analysis"
author: "Antoneely Calizaya"
date: "12/6/2021"
output: html_document
---

```{r}
library(tidyverse)
library(rtweet)
library(tidytext)
library(lubridate)
library(knitr)
library(emo)
library(topicmodels)
library(tm)
library(wordcloud)
library(wordcloud2)
library(RColorBrewer)
library(textrecipes)
library(tidymodels)
library(formattable)
library(broom)
library(ranger)
library(yardstick)
```

```{r}
remote_working_tweets<-read_csv("final_remote_working.csv")

```

```{r}
#adjusting time stamp
remote_working_tweets<-
  remote_working_tweets%>%
  mutate(
    timestamp=ymd_hms(created_at),
    day_of_week=wday(timestamp),
    id=as_factor(row_number())
  )
```

```{r}
# cleaning data
remove_reg <- "&amp;|&lt;|&gt;|\\d+\\w*\\d*|#\\w+|[^\x01-\x7F]|[[:punct:]]|https\\S*"
# &amp = @
# &lt;= <
# &gt; >


tidy_tweets <- remote_working_tweets %>% 
  filter(!str_detect(text, "^RT")) %>%
  mutate(text = str_remove_all(text, remove_reg)) 


tidy_tweets<-tidy_tweets%>%
  unnest_tokens(word, text, token = "tweets") 

tidy_tweets<-tidy_tweets%>%
  filter(
    str_detect(word, "[a-z]")
  )%>%
  anti_join((stop_words))

head(tidy_tweets$word)

```

```{r}
tidy_tweets%>%
  filter(word != "remote working")%>%
  count(word)%>%
  top_n(20)%>%
  arrange(desc(n))
```
```{r}
#wordcloud
tidy_tweets%>%
  filter(word != "bitcoin")%>%
  with(wordcloud(words = word, max.words = 100))
```


```{r}
#most retweeted tweets
remote_working_tweets %>% 
  arrange(-retweet_count) %>%
  select(created_at, screen_name, text, retweet_count)%>%
  top_n(20)
```

```{r}
#sentiment libraries
afinn<-get_sentiments("afinn")
bing<-get_sentiments("bing")
nrc<-get_sentiments("nrc")
```
```{r}
#bing sentiment analysis
#joining bing library to data
sentiment_tidy_tweets <- tidy_tweets%>%
  inner_join(nrc)
sentiment_tidy_tweets%>%head()
#adding a data coloumn bassed on timestamp
sentiment_tidy_tweets<-sentiment_tidy_tweets%>%
  mutate(date = date(timestamp))
```

```{r}
selected_tweets_tidy<-tidy_tweets%>%select(timestamp, day_of_week, location, word, user_id)

selected_tweets_tidy<-selected_tweets_tidy%>%
  inner_join(bing)%>%
  rename(sentiment_bing=sentiment)%>%
  inner_join(nrc)%>%
  rename(sentiment_nrc=sentiment)


selected_tweets_tidy%>%
  count(sentiment_nrc, sort=TRUE)


```

```{r}
#counting positive and negative words by date
sentiment_tidy_tweets%>%
  group_by(date)%>%
  count(sentiment)%>%
  ungroup()
```
```{r}
#visualise counts of positve and negative words over timeperiod
sentiment_tidy_tweets%>%
  ggplot(aes(date, fill = sentiment))+
  geom_bar()
```
```{r}
#count of word
sentiment_tidy_tweets%>%
  count(word)%>%
  arrange(desc(n))

#count by sentiment
sentiment_tidy_tweets%>%
  group_by(sentiment)%>%
  summarise(avg_retweet_by_sentiment = mean(retweet_count),n=n())%>%
  arrange(desc(avg_retweet_by_sentiment))
```
