#Import module
import pandas as pd

#Reading csv and json files
order_details_df = pd.read_csv("order_details.csv")
pc_df = pd.read_json("pc.json")

#Renaming column for merging
order_details_df = order_details_df.rename(columns={"product_category_id":"category_id"})

#Calculating total revenue by category id
order_details_df["revenue"] = order_details_df["unit_price"] * order_details_df["quantity"]
cat_id_and_rev = order_details_df[["category_id","revenue"]]
groupby_pc = cat_id_and_rev.groupby(["category_id"]).sum()
highest_revenue = max(groupby_pc["revenue"])

#Dataset for output
highest_revenue_row = groupby_pc.query("revenue == @highest_revenue")
high_rev_with_dets = pd.merge(highest_revenue_row, pc_df,
                   on='category_id',
                   how='inner')

#Print outputs
print(f"Category ID number {high_rev_with_dets['category_id'].values[0]} has the highest revenue.")
print(f"The name of the category is {high_rev_with_dets['category_name'].values[0]}, and consists of {high_rev_with_dets['description'].values[0]}.")
print(f"The total revenue generated by this category is ${high_rev_with_dets['revenue'].values[0]:8,.2f}.")


